name: nos
base: core22
version: '1.1.6'
summary: Beautiful Nostr CLI Client
description: |
  A beautiful command-line client for posting to Nostr, built with Go and Charm.sh.
  
  Features:
  - Secure key storage using system keyring
  - Beautiful terminal UI with Charm.sh
  - Posts to multiple relays for reliability
  - Simple one-command posting
  - Customizable relay management
  - Account switching with complete reset
  - Interactive menu-driven interface
  - Post verification across relays

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  nos:
    command: bin/nos
    plugs:
      - network
      - network-bind
      - home
      - password-manager-service

parts:
  nos:
    plugin: go
    source: .
    build-packages:
      - git
    stage-packages:
      - ca-certificates
    override-build: |
      export CGO_ENABLED=0
      export GOOS=linux
      export GOARCH=$CRAFT_TARGET_ARCH
      case $CRAFT_TARGET_ARCH in
        amd64) export GOARCH=amd64 ;;
        arm64) export GOARCH=arm64 ;;
        armhf) export GOARCH=arm ;;
      esac
      go build -ldflags="-s -w" -o $SNAPCRAFT_PART_INSTALL/bin/nos .