name: Build and Publish Snap

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build snap
      uses: snapcore/action-build@v1
      id: build
    
    - name: Upload snap artifact
      uses: actions/upload-artifact@v4
      with:
        name: snap
        path: ${{ steps.build.outputs.snap }}
    
    - name: Publish to edge
      if: github.ref == 'refs/heads/main'
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
    
    - name: Publish to stable
      if: startsWith(github.ref, 'refs/tags/v')
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: stable