name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go build -ldflags "-s -w" -o nos.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nos-windows
          path: nos.exe
